-- =============================================================================
-- 🚀 E-COMMERCE MICROSERVICES DATABASE INITIALIZATION (POSTGRESQL)
-- =============================================================================
-- This script contains the DDL schemas for all databases and tables.
-- Note: When running locally via Docker Compose, these databases are created 
-- by 'db-init.sh' and the tables are automatically generated by Flyway.
-- =============================================================================

-- 1. USER DATABASE & TABLES
SELECT 'Creating User Database...';
\c postgres
CREATE DATABASE user_db;
\c user_db

CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE refresh_tokens (
    id BIGSERIAL PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);


-- 2. PRODUCT DATABASE & TABLES
SELECT 'Creating Product Database...';
\c postgres
CREATE DATABASE product_db;
\c product_db

CREATE TABLE categories (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE products (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    category VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- 3. INVENTORY DATABASE & TABLES
SELECT 'Creating Inventory Database...';
\c postgres
CREATE DATABASE inventory_db;
\c inventory_db

CREATE TABLE inventory (
    id BIGSERIAL PRIMARY KEY,
    product_id BIGINT NOT NULL UNIQUE,
    quantity INTEGER NOT NULL
);


-- 4. ORDER DATABASE & TABLES
SELECT 'Creating Order Database...';
\c postgres
CREATE DATABASE order_db;
\c order_db

CREATE TABLE orders (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
    id BIGSERIAL PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);


-- 5. PAYMENT DATABASE & TABLES
SELECT 'Creating Payment Database...';
\c postgres
CREATE DATABASE payment_db;
\c payment_db

CREATE TABLE payments (
    id BIGSERIAL PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    amount NUMERIC(10, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    transaction_id VARCHAR(100) NOT NULL UNIQUE,
    payment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- 6. CART DATABASE & TABLES (Legacy Module Support)
SELECT 'Creating Cart Database...';
\c postgres
CREATE DATABASE cart_db;
\c cart_db

CREATE TABLE cart (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00
);

CREATE TABLE cart_items (
    id BIGSERIAL PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE
);
