server:
  port: 8082

spring:
  cache:
    type: simple
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: "180904"
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379

