spring:
  cloud:
    gateway:
      routes:
        - id: user-service-auth
          uri: http://user-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - name: JwtAuthFilter
              args:
                secured: false

        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - JwtAuthFilter

        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/api/products/**
          filters:
            - JwtAuthFilter

        - id: category-service
          uri: http://product-service:8082
          predicates:
            - Path=/api/categories/**
          filters:
            - JwtAuthFilter

        - id: cart-service
          uri: http://cart-service:8083
          predicates:
            - Path=/api/cart/**
          filters:
            - JwtAuthFilter

        - id: order-service
          uri: http://order-service:8084
          predicates:
            - Path=/api/orders/**
          filters:
            - JwtAuthFilter

        - id: recommendation-service
          uri: http://recommendation-service:8000
          predicates:
            - Path=/api/recommendations/**
          filters:
            - JwtAuthFilter
